name: Release & Publish Package

on:
  release:
    types: [released, prereleased]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e #v4.3.0
        with:
          node-version: 22
      - run: npm ci
      # - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e #v4.3.0
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm run build
      - id: publish-prerelease
        if: github.event.release.prerelease
        run: npm publish --tag prerelease
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PACKAGE_REGISTRY_TOKEN}}
      - id: npm-publish-latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PACKAGE_REGISTRY_TOKEN}}
        run: npm publish
      - id: set-dist-tag-latest
        if: ${{steps.npm-publish-latest.outcome.failure}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PACKAGE_REGISTRY_TOKEN}}
        run: |
          VERSION=$(npm pkg get version | jq . -r)
          npm dist-tag add sats-connect@$VERSION latest
