name: Release & Publish Beta Package for Pull Requests

on:
  pull_request:
    branches: [develop]

  workflow_dispatch:

jobs:
  fork-check:
    runs-on: ubuntu-latest
    outputs:
      is-not-fork: ${{ steps.check.outputs.is_not_fork }}
    steps:
      - id: check
        run: echo "::set-output name=is_not_fork::${{ github.repository == 'secretkeylabs/sats-connect' }}"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e #v4.3.0
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      # TODO: enable linting once ready
      # - run: npm run lint
      # - run: npm test

  publish-beta:
    needs:
      - test
      - fork-check
    if: needs.fork-check.outputs.is-not-fork == 'true'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e #v4.3.0
        with:
          node-version: 24
          cache: npm
          registry-url: https://registry.npmjs.org

      - id: git-commit
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - run: npm ci
      - run: npm run build

      - id: current-version
        run: echo "version=$(npm pkg get version  | tr -d '"')" >> $GITHUB_OUTPUT
      - id: tag-version
        run: npm version --no-git-tag-version $CURRENT_VERSION-$SHA
        env:
          SHA: ${{ steps.git-commit.outputs.sha }}
          CURRENT_VERSION: ${{ steps.current-version.outputs.version }}

      - id: publish
        run: npm publish --tag pr
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PACKAGE_REGISTRY_TOKEN}}

      - id: published-version
        run: echo "version=$(npm pkg get version  | tr -d '"')" >> $GITHUB_OUTPUT
      - run: echo published version $VERSION
        env:
          VERSION: ${{ steps.published-version.outputs.version }}

      - name: Add package pre-release info
        uses: secretkeylabs/github-actions/add-package-pre-release-info-to-pr@main
        with:
          package-name: "sats-connect"
          version: ${{ steps.published-version.outputs.version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}
